### PR TITLE
added code for demo of affiliates connect

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by dbjpanda** [comment]
Can you first send a pull request to https://github.com/shibasisp/feeds_advance_crawler_backend/tree/a884d5d6ecbcadf7396c7415520a646a66ceb22a adding a docker directory and configuring everything there ?  Because that repo is added as a submodule to this demo repo. If you will update there then it will be reflected here as well . :)

**Comment by ankitjain28may** [comment]
@dbjpanda I have added that file in the backend repo. I have cloned the repo and on cloning, it is not showing pr cloning the files of that repo. I don't know much about submodules in GitHub.

**Comment by dbjpanda** [comment]
git clone --recursive https://github.com/dbjpanda/affiliates_connect_demo.git 

Just need to pass a parameter " --recursive"

**Comment by dbjpanda** [comment]
Closing it. You just now push your exported configuration and set up travis to deploy it on ankitjain.me

**Pull request closed without merging**
