### PR TITLE
Fix travis #14

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by dbjpanda** [comment]
@ankitjain28may Can you please squash it ?

**Comment by ankitjain28may** [comment]
@dbjpanda You can squash and merge it.

**Comment by dbjpanda** [comment]
@ankitjain28may  I know that. But if you could quash it, I can easily check it using github web. 
And is it necessary to provide a hash salt ? Because it is unique for every site installation and automatically generated by Drupal.

**Comment by ankitjain28may** [comment]
@dbjpanda Yes, It is automatically generated by the Drupal during Drupal installation so in case we have existing drupal code but no settings.php file, we copy the default.settings.php and add the database content through ScriptHandler but hash_salt isn't added so either we have to defined the hash_salt in default.settings.php or we can use salt.txt file in which we can add the hash_salt string and load the content from that file.

**Comment by ankitjain28may** [comment]
@dbjpanda I have squashed the commits.

**Comment by dbjpanda** [comment]
@ankitjain28may But pushing db is not good idea. I am merging it now. Later you should push the config and content only as I had done in blogenic repo. Also check your hangout. I had sent you one message there.

**Pull request merged**
